limits:
    item-damage: 35         #Maximum damage% with which a shop will accept an item. Limit of 35 damage here means require at least 65% durability remaining. Needed because item damage is discarded when adding to stock.
    find-distance: 1500     #Block radius to include shops in "find" results. 0 = Unlimited
    shops-per-player: -1    #Maximum number of shops each player can have; Unlimited = -1
fees:
    create: 100.0           #Cost of creating a shop; 0 = free
    move: 10.0              #Cost of moving a shop; 0 = free
log:
    limit: 500              #Maximum number of transactions saved in log per shop.
    notify-interval: 300    #Number of seconds between transaction notifications; 0 = Disable notifications
size:
    max-height: 10          #Maximum custom shop height.
    max-width: 30           #Maximum custom shop width (both horizontal dimensions).
storage:
    system: sqlite          #Can be sqlite (file) or mysql (server)
    connect:                #These params only needed if system = mysql
        host: localhost     #Where the database server is located
        port: 3306          #Port number that the database server is listening on
        user: minecraft     #Username to connect to the database server
        pass: password      #Password to connect to the database server
        db: commandshops    #Name of the database containing CommandShops data
regions:
    require-owner: false;   #Require all created/moved shops to be tied to a region owned by the shop owner
debug: false                #Enable verbose debug output.
custom-items: false         #Use custom item set from items.yml. When False, CS will make its own items.yml with the vanilla items.