name: LocalShops
main: net.centerleft.localshops.LocalShops
version: 1.12b
author: Jonbas
description: >
             A localized shop plugin for use with iConomy.
             Users can create and manage their own shops.
commands:
  lshop:
    description: Command for managing shops 
    usage: |
           /<command> - displays command help
